"""
Regenerate Pydantic models under generated/ from the JSON Schema 2020-12
contracts under contracts/.

generated/ is never hand-edited (Section 17.4). This script is the single
entrypoint both CI and local dev use to (re)produce it, so that running it
twice against an unchanged contracts/ tree yields byte-identical output
(Increment 1's acceptance test: "model generation is reproducible from
schema").

Two robustness details, both discovered by this script actually failing
once during development:

1. contracts/ also holds validators.py and __init__.py (Python source,
   co-located with the schemas deliberately) plus whatever __pycache__/
   *.pyc files running pytest leaves behind. datamodel-code-generator's
   directory-mode input walks every file under the given path, and a
   binary .pyc file crashes it with a UnicodeDecodeError. To keep codegen
   robust against any non-schema file that happens to live under
   contracts/ - now or in the future - this script copies only *.json
   files into a temporary directory (preserving relative structure, so
   $ref paths still resolve) and points datamodel-code-generator at that
   instead of contracts/ directly.

2. Generation must not destroy the existing generated/ output before
   confirming the new run actually succeeded - a crash mid-run must not
   leave generated/ empty. Generation therefore runs into a fresh
   temporary directory first; the real generated/ is only replaced once
   that succeeds.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CONTRACTS_DIR = REPO_ROOT / "contracts"
GENERATED_DIR = REPO_ROOT / "generated"


def _stage_schema_only_copy(staging_dir: Path) -> None:
    for schema_path in CONTRACTS_DIR.rglob("*.json"):
        relative = schema_path.relative_to(CONTRACTS_DIR)
        destination = staging_dir / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(schema_path, destination)


def _datamodel_codegen_args(input_dir: Path, output_dir: Path) -> list[str]:
    return [
        "--input", str(input_dir),
        "--input-file-type", "jsonschema",
        "--output", str(output_dir),
        "--output-model-type", "pydantic_v2.BaseModel",
        "--target-python-version", "3.12",
        "--use-schema-description",
        "--use-field-description",
        "--use-subclass-enum",
        "--collapse-root-models",
        "--use-standard-collections",
        "--use-union-operator",
        "--strict-nullable",
        "--disable-timestamp",
        "--field-constraints",
        "--use-annotated",
        # Without this, datamodel-code-generator embeds the (randomly
        # named) staging directory's path into each file's header comment,
        # which breaks byte-for-byte reproducibility across runs - the
        # staging directory exists only so *.pyc/__pycache__ cruft under
        # contracts/ can't reach the generator (see module docstring), and
        # its name must not leak into the output.
        "--custom-file-header", "# generated by datamodel-codegen:\n#   source: contracts/",
        "--custom-file-header-mode", "replace",
    ]


def main() -> int:
    with tempfile.TemporaryDirectory(prefix="cmgp-contracts-") as staging_str:
        staging_dir = Path(staging_str)
        _stage_schema_only_copy(staging_dir)

        with tempfile.TemporaryDirectory(prefix="cmgp-generated-") as out_str:
            output_staging = Path(out_str)

            result = subprocess.run(
                [sys.executable, "-m", "datamodel_code_generator",
                 *_datamodel_codegen_args(staging_dir, output_staging)],
                cwd=REPO_ROOT,
            )
            if result.returncode != 0:
                return result.returncode

            (output_staging / "py.typed").touch()

            if GENERATED_DIR.exists():
                for entry in GENERATED_DIR.iterdir():
                    if entry.name in {".gitkeep", "README.md"}:
                        continue
                    if entry.is_dir():
                        shutil.rmtree(entry)
                    else:
                        entry.unlink()
            GENERATED_DIR.mkdir(parents=True, exist_ok=True)

            for entry in output_staging.iterdir():
                destination = GENERATED_DIR / entry.name
                if entry.is_dir():
                    shutil.copytree(entry, destination)
                else:
                    shutil.copy2(entry, destination)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
